/**
 * Build the standalone gallery into `docs/static/gallery/`.
 *
 * Pipeline:
 *  1. Scan cards via the shared `TEMPLATE_SOURCES` config (single source of
 *     truth with `build.ts`, so exclusions stay consistent).
 *  2. Generate `gallery/src/.generated/cards.ts` — a strongly-typed manifest
 *     of every card the gallery should show, with dynamic `import()` loaders
 *     using static relative paths (Vite can analyze + chunk them).
 *  3. Programmatically run Vite build using `gallery/vite.config.ts`.
 *
 * Run AFTER `pnpm build:registry` (so the JSON registry is published) and
 * AFTER `node scripts/extra-registry/build.ts` (extra items merged in).
 * Output ends up alongside `static/registry/`, so the same Pages/CF deploy
 * step ships both the gallery and the installable JSON.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build as viteBuild } from "vite";

import { TEMPLATE_SOURCES, EXAMPLE_SOURCES, EXCLUDED_SLUGS, EXCLUDED_EXAMPLES } from "./config.js";
import { deriveTags, readMeta, toTitleCase } from "./shared.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const galleryDir = path.join(__dirname, "gallery");
const generatedDir = path.join(galleryDir, "src", "lib", "__generated__");
const generatedFile = path.join(generatedDir, "cards.ts");

interface Entry {
	name: string;
	slug: string;
	group: string;
	title: string;
	description: string;
	categories: string[];
	absSveltePath: string;
}

function collect(): Entry[] {
	const out: Entry[] = [];
	for (const { group, dir } of TEMPLATE_SOURCES) {
		if (!fs.existsSync(dir)) continue;
		for (const entry of fs.readdirSync(dir)) {
			if (!entry.endsWith(".svelte")) continue;
			const slug = entry.replace(/\.svelte$/, "");
			if (EXCLUDED_SLUGS.has(`${group}/${slug}`)) continue;
			const abs = path.join(dir, entry);
			const meta = readMeta(abs);
			out.push({
				name: `tpl-${group}-${slug}`,
				slug,
				group,
				title: meta?.title ?? toTitleCase(slug),
				description: meta?.description ?? "",
				categories: meta?.categories ?? deriveTags(slug, group),
				absSveltePath: abs,
			});
		}
	}
	// Multi-file examples: load each folder's `+page.svelte` as the preview.
	for (const { group, root, categories } of EXAMPLE_SOURCES) {
		if (!fs.existsSync(root)) continue;
		for (const ent of fs.readdirSync(root, { withFileTypes: true })) {
			if (!ent.isDirectory()) continue;
			const slug = ent.name;
			if (EXCLUDED_EXAMPLES.has(slug)) continue;
			const pageFile = path.join(root, slug, "+page.svelte");
			if (!fs.existsSync(pageFile)) continue;
			out.push({
				name: `tpl-${group}-${slug}`,
				slug,
				group,
				title: toTitleCase(slug),
				description: `"${slug}" example page from the shadcn-svelte docs site.`,
				categories: [...categories, slug],
				absSveltePath: pageFile,
			});
		}
	}
	out.sort((a, b) => a.name.localeCompare(b.name));
	return out;
}

function toPosix(p: string): string {
	return p.split(path.sep).join("/");
}

function generateIndex(entries: Entry[]): void {
	fs.mkdirSync(generatedDir, { recursive: true });
	const lines: string[] = [
		"// AUTO-GENERATED by docs/scripts/extra-registry/build-gallery.ts",
		"// Do not edit by hand. Re-run the build to refresh.",
		"",
		"export interface CardEntry {",
		"\tname: string;",
		"\tslug: string;",
		"\tgroup: string;",
		"\ttitle: string;",
		"\tdescription: string;",
		"\tcategories: string[];",
		"\tloader: () => Promise<{ default: import('svelte').Component }>;",
		"}",
		"",
		"export const cards: CardEntry[] = [",
	];
	for (const e of entries) {
		const rel = toPosix(path.relative(generatedDir, e.absSveltePath));
		lines.push("\t{");
		lines.push(`\t\tname: ${JSON.stringify(e.name)},`);
		lines.push(`\t\tslug: ${JSON.stringify(e.slug)},`);
		lines.push(`\t\tgroup: ${JSON.stringify(e.group)},`);
		lines.push(`\t\ttitle: ${JSON.stringify(e.title)},`);
		lines.push(`\t\tdescription: ${JSON.stringify(e.description)},`);
		lines.push(`\t\tcategories: ${JSON.stringify(e.categories)},`);
		lines.push(`\t\tloader: () => import(${JSON.stringify(rel)}),`);
		lines.push("\t},");
	}
	lines.push("];", "");
	fs.writeFileSync(generatedFile, lines.join("\n"));
}

async function main(): Promise<void> {
	const entries = collect();
	if (entries.length === 0) {
		console.warn("[gallery] no cards discovered; skipping build.");
		return;
	}
	console.log(`[gallery] discovered ${entries.length} card(s); generating manifest…`);
	generateIndex(entries);
	if (process.env.GALLERY_MANIFEST_ONLY === "1") {
		console.log("[gallery] GALLERY_MANIFEST_ONLY=1 → skipping vite build.");
		return;
	}
	console.log(`[gallery] running vite build…`);
	await viteBuild({
		root: galleryDir,
		configFile: path.join(galleryDir, "vite.config.ts"),
	});
	console.log(`[gallery] done → docs/static/gallery/`);
}

main().catch((err) => {
	console.error("[gallery] build failed:", err);
	process.exitCode = 1;
});
