/**
 * A self-contained, lucide-only drop-in for the docs-site `IconPlaceholder`
 * component. Emitted alongside any template card that imports the original,
 * so installed blocks have zero dependency on docs-site internals.
 *
 * The original supports five icon libraries; the CLI default is `lucide`, so
 * the shim only honours the `lucide` prop and ignores the rest.
 */
export const ICON_PLACEHOLDER_SHIM = `<script lang="ts">
	// Auto-generated by the custom registry build.
	// Replaces the docs-site IconPlaceholder with a lucide-only version so the
	// template card is self-contained.
	import { type Component } from "svelte";
	import SquareIcon from "@lucide/svelte/icons/square";
	import type { SVGAttributes } from "svelte/elements";

	type SvgProps = SVGAttributes<SVGSVGElement>;

	type Props = {
		lucide?: string;
		// Accepted but ignored — kept so the original card source compiles unchanged.
		hugeicons?: string;
		tabler?: string;
		phosphor?: string;
		remixicon?: string;
		class?: string;
	};

	let {
		lucide,
		class: className,
		...restProps
	}: Props & Omit<SvgProps, "class"> = $props();

	let IconComp = $state<Component<SvgProps> | null>(null);

	$effect(() => {
		if (!lucide) return;
		// Dynamic import keeps tree-shaking working in consumers' builds.
		const importer = (name: string) =>
			import(/* @vite-ignore */ \`@lucide/svelte/icons/\${toKebab(name)}\`);
		importer(lucide)
			.then((m) => (IconComp = m.default as Component<SvgProps>))
			.catch(() => (IconComp = null));
	});

	function toKebab(name: string): string {
		// "CheckCircle2Icon" → "check-circle-2"
		return name
			.replace(/Icon$/, "")
			.replace(/([a-z])([A-Z])/g, "$1-$2")
			.replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
			.toLowerCase();
	}
</script>

{#if IconComp}
	<IconComp class={className} {...restProps as unknown as object} />
{:else}
	<SquareIcon class={className} {...restProps as unknown as object} />
{/if}
`;
